### ISSUE TITLE
404 for https://dl.dropbox.com/u/597777/symfony-quantal32.box

### ISSUE THREAD

**Issue by jekill** [KunstmaanLegacy/KunstmaanSandbox#71]
Hello.
After the launch of <code>"vagrant up"</code>, I get:

``` bash
~/projects/kuns$ vagrant up
[default] Box symfony-quantal32 was not found. Fetching box from specified URL...
[vagrant] Downloading with Vagrant::Downloaders::HTTP...
[vagrant] Downloading box: https://dl.dropbox.com/u/597777/symfony-quantal32.box
Bad status code: 404

Please verify that the box exists and is accessible. Also verify that
this computer is properly connected to the internet.
```

**Comment by sgasser** [comment]
Same error: https://dl.dropbox.com/u/597777/symfony-quantal32.box does not exists anymore

**Comment by roderik** [comment]
Damn, I will get another box up asap. Better not depend on some dropbox url :)

**Comment by roderik** [comment]
Updated the box url with a new box. Fixed in https://github.com/Kunstmaan/KunstmaanSandbox/commit/ec78ba9db45418292078d3e1bc80636ac521cfa5
