### ISSUE TITLE
Can't add a submit button to a form within sandbox

### ISSUE THREAD

**Issue by rickpastoor** [KunstmaanLegacy/KunstmaanSandbox#72]
Hi there,

I don't know if this is a limitation of the sandbox, or that the sandbox uses a different version of the kunstmaan/form-bundle, but I am not able to add a submit button to a form I've created.

This is the list of pageparts that I can use:

![Schermafbeelding 2013-04-12 om 12 53 03](https://f.cloud.github.com/assets/149958/372511/2853d2a2-a35f-11e2-899c-7397521a6f98.png)

Might be a version thing, but if so, it would be smart to upgrade the sandbox bundle to include the latest. Or am I doing something wrong?

**Comment by krispypen** [comment]
There are indeed some missing pageparts in the generated FormPagePagePartAdminConfigurator.php, here you can see what needs to be added: https://github.com/Kunstmaan/KunstmaanGeneratorBundle/pull/19/files

**Comment by Mopster** [comment]
The submit button has been added to the skeleton of the generator, so future generations have it by default. I'm closing this issue now, feel free to open an issue if there are any more questions.
