### ISSUE TITLE
Don't tie the remember_me option to the sandbox.kunstmaan.be domain

### ISSUE THREAD

**Issue by rickpastoor** [KunstmaanLegacy/KunstmaanSandbox#73]
https://github.com/Kunstmaan/KunstmaanSandbox/blob/master/app/Resources/tools/install_scripts/security-singlelang.dist.yml#L37

As stated in the docs: it would be better to use ~. Symfony will use the current domain from $_SERVER.

Or is there a specific reason to do this?

**Comment by Mopster** [comment]
Thanks for the notice, we changed it in the dist files.
