### ISSUE TITLE
just a few comments about the getting started script

### ISSUE THREAD

**Issue by bichotll** [KunstmaanLegacy/KunstmaanSandbox#76]
Hi there!

First of all, really good job!

I'm just seeing the "Getting Started" guide and I saw some things to improve or ask:
- "ruby -e "require 'open-u[...]" in this machine I don't have ruby.
- "sudo chown -R $PROJECTNAME web/uploads" this is not my case...$PROJECTNAME for a user permisions...are you sure?

For me no problem, but I was just a few comments ;)

Cheers

**Comment by SpoBo** [comment]
Hey @bichotll. Thanks for the feedback. Sadly we do require ruby to be installed to run the sandboxinstaller. As we use OS X & unix based environments in our shop this was a natural fit to quickly get something up & running. However, it does make sense to do this in PHP. We'll put it on our roadmap and evaluate it.

Setting the projectname as the user is a policy here as we require a different username per project. It's pretty secure and it actually makes a lot of sense in our environment. I think we removed this from the installer however. We have a different tool (https://github.com/Kunstmaan/kDeploy) that sets this up for us.

So, suggestions received. We'll check to do the installer in PHP and the chmod projectname web/uploads shouldn't be a problem anymore.
