### ISSUE TITLE
Seems to be a problem with the box url in Vagrant file

### ISSUE THREAD

**Issue by denito** [KunstmaanLegacy/KunstmaanSandbox#78]
I get this error when I attempt vagrant up:

[default] Box 'kunstmaan-vagrant-raring64' was not found. Fetching box from specified URL for the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.

**Comment by roderik** [comment]
I've updated the box url, it should work.

**Comment by kimausloos** [comment]
Closing as this is fixed.
