### ISSUE TITLE
Doesn't RoutingExtraBundle needs to be replaced by RoutingBundle for Symfony 2.2?

### ISSUE THREAD

**Issue by ghost** [KunstmaanLegacy/KunstmaanSandbox#80]
I do love this bundles, me and my team would like to get started with this!

This is a question I came across while studying the bundles

**Comment by Mopster** [comment]
This is a change for Symfony2.3, which we are in the process of upgrading our bundles for. :-)

**Comment by ghost** [comment]
Nice work! When I have read into the documentation and bundles I also would like to contribute more
